### ISSUE TITLE
Youtube embeds do not render inside some shortcodes

### ISSUE THREAD

**Issue by tjsuw** [uweb/uw_wp_theme#11]
This may be expected behavior, but investigate.

Tried inside Modal that was inside Tabs (modal renders fine inside tabs) and the Youtube link didn't embed.

Tried just inside Tabs and the YouTube link didn't embed.

YouTube link embeds on page.

YouTube link also embeds inside a Modal on the page. So this could be Tabs specific, even though shortcodes work in the tabs.

YouTube link also embeds inside an accordion so this is looking more and more like a glitch with Tabs.

**Comment by lcaple** [comment]
Teri, this seems to be an issue with _how_ the youtube is embedded into shortcodes. Since we have `do_shortcode` on a majority of our shortcodes, if you add a youtube video with either the `[embed]` shortcode or our `[youtube]` shortcode, it works. If you simply copy and past the URL, the content processors can't do their magic. 

I think for Modals it makes sense to use `apply_filter( 'the_content', $content )` for now and see if it causes issues. I hesitate to do it in other spots by default.

Ultimately the `[embed]` and old `[youtube]` and `[iframe]` shortcodes work and folks can take advantage of those in other spots. But I think we should weigh adding youtube embeds to other shortcodes after I implement this fix.

Adding it to the next round of bug fixes.

**Comment by lcaple** [comment]
I've got this working in modals on the [latest release](https://github.com/uweb/uw_wp_theme/releases/tag/1.2.0).

@tjsuw @tifsev Any particular thoughts about adding support for specifically auto-discovering embed links (copying https://www.youtube.com/watch?v=gOmiwd2HS_c and having it show the embed as opposed to using the embed shortcode) from URLs to shortcodes?
