### ISSUE TITLE
Installation instructions lead to missing styles

### ISSUE THREAD

**Issue by bonifacp** [uweb/uw_wp_theme#14]
Following the installation instructions in the readme creates problems. Using either the "Download ZIP", or the release source code zip file ends up with extra text in the theme directory name. For example if you use the release source code you get a theme directory in wordpress called "uw_wp_theme-1.1.1", while downloading the master branch zip creates "uw_wp_theme-master". Certain styles will not load when installed this way, and it can cause problems with updating versions on each release.

Installation via SFTP works fine, but you still need to rename the theme directory.

**Comment by lcaple** [comment]
Thanks for letting us know. We'll update the instructions to indicate the theme directory needs to be `uw_wp_theme`.

**Comment by bonifacp** [comment]
Any chance of using a different release mechanism that plays nice with Wordpress' theme system?

**Comment by lcaple** [comment]
In terms of the mechanism, our team is going to continue to use GitHub to manage all of our releases.

I highly recommend using git itself to clone the repo and do updates, which you can either pull down on your local machine and then update on the server or install git directly on your server and use that to manage updates. 

Otherwise, downloading the master branch (which will always be up-to-date with the latest release) and making sure to rename the folder to remove "-master" is a good tactic when updating.

I have heard there are also third party plugins that can manage your git-based theme/plugin updates. I don't have experience with them myself, but let me know if you end up exploring any of them!

**Comment by lcaple** [comment]
I've got this updated in the [latest release](https://github.com/uweb/uw_wp_theme/releases/tag/1.2.0), but I've also noticed that other folks using GitHub to manage WordPress themes and plugins manually build their own release artifacts to solve for this problem. This is a non-issue for a git based workflow but a problem for zip based ones. 

I'm adding manually building the releases to our process so now if you download it from the [release page](https://github.com/uweb/uw_wp_theme/releases/tag/1.2.0), it will install to the proper `uw_wp_theme` folder.
