### ISSUE TITLE
Current page indicator on sidebar menu

### ISSUE THREAD

**Issue by lcaple** [uweb/uw_wp_theme#27]
From Andy Krikawa:

**The issue**
Today, I discovered a minor issue in the sidebar menu in the new WP theme. The quickest way to explain it:

1. Visit: [This page](https://ciso.uw.edu/about-us/services/) (I’m using this page as I learned that CISO is using the new theme during Web Council last week!)
1. Look at the sidebar menu. Services, should have the border-left 10px solid gold. Another rule is winning out. Unless, this is intentional and part of the new theme.

Maybe the specificity of
`ul.uw-sidebar-menu li.pagenav ul li.current_page_ancestor ul.children li a`
is winning out over
`ul.uw-sidebar-menu li.pagenav ul li.current_page_parent a, ul.uw-sidebar-menu li.pagenav ul li.current_page_item a`

 
**Current theme**
An example of a sidebar menu having the border is: https://www.washington.edu/brand/web/guides-and-how-tos/.

**Comment by kris-zekteck** [comment]
This appears to be because the element is a hyperlink. On the working example given, the sidebar item is a span whereas the page with the broken styling has the item as a hyperlink. What I'm assuming is happening is that the working page is programmatically converting the hyperlink into a span once it is the active page and the broken page is failing to do so.
