### ISSUE TITLE
UW recent post widget - reverese order

### ISSUE THREAD

**Issue by NorbertBerger** [uweb/uw_wp_theme#65]
I'm using the UW recent posts widget, but it ends up not being recent posts.  instead of listing the newest posts first, it starts at the beginning (oldest posts first). and shows the first x number of posts to the site.  Is there a way to reverse this?

**Comment by lcaple** [comment]
I am unable to reproduce this issue on the latest version of the theme. The function used to create the list of posts is `wp_get_recent_posts()` which defaults to descending (newest first) order.

This issue might be caused by something else on your WordPress instance. Are you using a child theme or any plugins?

**Comment by NorbertBerger** [comment]
Lauren,

Never mind.  It was me.  I have other UW Wordpress theme sites that didn’t have this problem.  I was able to isolate the problem to a plugin.

If I enable the Simple Custom Posts Order<https://wordpress.org/plugins/simple-custom-post-order/> plugin it reverses the order of the posts.

Thanks for the quick response.

*******************************************
Norbert Berger - Computing Services Manager
Bioengineering - University of Washington
N125 Foege Box 355061  (206) 543-9757
*******************************************
